apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=./Dockerfile"
        - "--context=./"
        - "--destination=501888036187.dkr.ecr.eu-central-1.amazonaws.com/app/devops-tool:latest"
  #     volumeMounts:
  #       # when not using instance role
  #       - name: aws-secret
  #         mountPath: /root/.aws/
  # restartPolicy: Never
  # volumes:
  #   # when not using instance role
  #   - name: aws-secret
  #     secret:
  #       secretName: aws-secret